### ISSUE TITLE
No module named 'models.cnn.configs.resnet_model_config_pb2'

### ISSUE THREAD

**Issue by tonyqtian** [uber-research/learning-to-reweight-examples#4]
Hi, thank you for open-sourcing learning-to-reweight-examples, interesting work!

When I tired the code about CIFAR experiments, there is a file missing exception:

  File "~/projects/cifar/cifar_train.py", line 54, in <module>
    from models.cnn.configs.resnet_model_config_pb2 import ResnetModelConfig
ModuleNotFoundError: No module named 'models.cnn.configs.resnet_model_config_pb2'

many scripts in cifar folder import this script resnet_model_config_pb2, but the file did not exist.
is it a public file that I should download from the internet?

**Comment by mengye-ren** [comment]
You should run `make` to build the proto buffer files.
